### ISSUE TITLE
why is poseidon::primitives::permute  private?

### ISSUE THREAD

**Issue by themighty1** [privacy-scaling-explorations/poseidon-gadget#3]
Hi, in our project we would like to create a `PermuteCircuit` like the one shown here https://github.com/privacy-scaling-explorations/poseidon-gadget/blob/764a682ee448bfbde0cc92a04d241fe738ba2d14/src/poseidon/pow5.rs#L605

However, unlike in your test here https://github.com/privacy-scaling-explorations/poseidon-gadget/blob/764a682ee448bfbde0cc92a04d241fe738ba2d14/src/poseidon/pow5.rs#L676 ,
we wouldn't be able to access `poseidon::primitives::permute` to compute the permutation in the clear since the method is private. 

Would you consider making that method public? Or is it private on purpose?

**Comment by davidnevadoc** [comment]
In this example, the `permute` primitive is computed to get a result against which to check the computation of the gadeget.
https://github.com/privacy-scaling-explorations/poseidon-gadget/blob/764a682ee448bfbde0cc92a04d241fe738ba2d14/src/poseidon/pow5.rs#L676
Do you need to compute the permutation independently, outside of the circuit? :thinking: @themighty1

**Comment by themighty1** [comment]
> Do you need to compute the permutation independently, outside of the circuit? 

yes, that's what we need it for @davidnevadoc

**Comment by davidnevadoc** [comment]
I imagine it was set to private because as the intention was to expose only the full hash. Having said this, I think is fine to make it `pub`.

This has been changed in #5, is there any other primitive that you need exposed? @themighty1
